name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch like 'master' or 'gh-pages'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Debug: List files before sed
      run: ls -l

    - name: Debug: Show index.html before sed
      run: cat index.html

    - name: Replace API Key Placeholder
      run: |
        # Replace the placeholder in index.html with the actual secret API key
        # We use sed for in-place replacement. Make sure the placeholder matches exactly.
        sed -i "s/PLACEHOLDER_GEMINI_API_KEY/${{ secrets.GEMINI_API_KEY }}/g" index.html
      shell: bash
    - name: Debug: Show index.html after sed
      run: cat index.html
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./ # Or the directory where your index.html resides if it's not the root
        # If your GitHub Pages is served from a specific branch (e.g., gh-pages), specify it:
        # publish_branch: gh-pages
        # This is a single-line comment
